target-version = "py312"
line-length = 88

[lint]
select = ["E", "F", "I", "N", "W", "UP", "S", "B", "A", "C4", "T20"]
ignore = [
    "S101",  # Use of assert
    "S311",  # Standard pseudo-random generators
]

[lint.per-file-ignores]
"**/migrations/*" = ["E501", "N806"]
"**/settings/*" = ["E501", "F403", "F405", "S104"]
"manage.py" = ["E402"]

[lint.isort]
known-first-party = ["mcp_method_hub", "apps"]
